elit/cart/urls.py
from django.urls import path
from . import views

# пути для отображения корзины
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, 
         name='cart_remove'),
]

elit/elit/urls.py
from django.contrib import admin
from django.urls import path, include  # Import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),  # Include cart.urls
    path('', include('main.urls', namespace='main')),  # Include main.urls
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)
    
    
    # приложение main отвечает за отображение главной страниц и каталога
    # cart отвечает за отображение корзины и ее функционал

elit/main/urls.py
from django.urls import path
from . import views

# создаем urls 
app_name = 'main'

urlpatterns = [
    # путь для отображения главной страницы
    path('', views.popular_list, name='popular_list'),
    # пцть для отображения каталога
    path('shop/', views.product_list, name='product_list'),
    # пкть для фильтрации по категориям
    path('shop/<slug:slug>/', views.product_detail,
         name='product_detail'), 
    
    path('shop/category/<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
]

elit/main/models.py
from django.db import models
from django.urls import reverse


class Category (models.Model):
    name = models.CharField(max_length=20, 
                            unique=True)
    # для создания уникального URL
    # для каждой категории
    slug = models.SlugField(max_length=20, 
                            unique=True)

    # отображение в админке
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def get_absolute_url(self):
        return reverse('main:product_list_by_category',
                        args=[self.slug]) 
 
    
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products', 
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=50, 
                            unique=True)
    slug = models.SlugField(max_length=50, 
                            unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, 
                                decimal_places=2)
    image = models.ImageField(upload_to='products/%Y/%m/%d',)
    # stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4,
                                   decimal_places=2)
    
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    
    
    def __str__(self):
        return self.name
    
    # url для отображения продукта по id
    def get_absolute_url(self):
        return reverse('main:product_detail',
                      args=[self.slug])
    
    # система скидок
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2 )
        return self.price    
     

elit/users/models.py
from django.db import models

# Create your models here.

elit/cart/forms.py
from django import forms

# для отображения формы добавления товара в корзину

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        # label='Quantity',
        # widget=forms.Select(attrs={'class': 'form-control'})
    )
    override = forms.BooleanField(required=False, 
                                  initial=False, 
                                  widget=forms.HiddenInput
    )   

elit/cart/views.py
from django.shortcuts import render, redirect, \
    get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm

#представление для отображения товара в корзину 


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail') 


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(
    #         initial={'quantity': item['quantity'],
    #                  'override': True
    return render(request, 'cart/detail.html', {'cart': cart})

elit/main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Category, Product
from cart.forms import CartAddProductForm

# для отображения глвавной страницы


def popular_list(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)[:4]
    # Неочевидно, чому саме ці 3 продукти — популярність не визначена
    return render(request, 
                  'main/index/index.html',
                  {'products': products})
    
def product_detail(request, slug):
    product = get_object_or_404(Product, 
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm     # создаем кнопку добавления товара в корзину
    return render(request,
                  'main/product/detail.html',
                  {'product': product, 
                   'cart_product_form': cart_product_form})   
    # словарь с данными для шаблона
    # в качестве значения передаем объект product 
    # ключ product может называться как угодно
    # в шаблоне мы обращаемся к объекту product
    

# каталог товаров
def product_list(request, category_slug=None):
    page = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, 1)
    current_page = paginator.page(int(page))
    
    if category_slug:
        category = get_object_or_404(Category, 
                                     slug=category_slug)
        products = products.filter(category=category)
        paginator = Paginator(products.filter(category=category), 1)
        current_page = paginator.page(int(page))     
    return render(request,
                  'main/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': current_page,
                   'slug': category_slug})

elit/users/views.py
from django.shortcuts import render

# Create your views here.

elit/cart/templates/cart/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Cart{% endblock title%}

{% block content %}
    <section class="cart d-flex">
        <div class="cart-title">
            <h2>Shopping Cart</h2>
        </div>
        <div class="cart-cards">
            {% for item in cart %}
                {% with product=item.product %}
                    <div class="cart-card d-flex">
                        <div class="cart-card-img">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimg.jpg' %}{% endif %}" alt="">
                        </div>
                        <div class="cart-card-info">
                            <div class="cart-card-name">
                                <p>{{ product.name }}</p>
                            </div>
                            <div class="cart-card-q">
                                <p>Quantity: {{ item.quantity }}</p>
                            </div>
                        </div>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                            <input type="submit" value="Remove" class="remove-btn">
                            {% csrf_token %} 
                            {% comment %}  не позволяет делать межсайтовые запросы {% endcomment %}
                        </form>
                        <div class="cart-card-price">
                            {% if product.discount %}
                                <div class="cart-discount d-flex gap-2"> 
                                    <p class="line">$ {{ product.price }}</p>
                                    <p>$ {{ product.sell_price }}</p>
                                </div>
                            {% else %}
                                <p class="price">$ {{ product.price }}</p>
                            {% endif %}
                        </div> 
                    </div>
                {% endwith %}
            {%endfor%}
        </div>
        <div class="total">
            <h5>Total sum: $ {{ cart.get_total_price }}</h5>
        </div>
        <div class="cart-buttons d-flex gap-3">
            {% comment %} иконка что будет вести в корзину {% endcomment %}
            <a href="/shop" class="cart-btn">Continue Shopping</a>
            {% with cart_quantity=cart|length %}
                {% if cart_quantity > 0 %}  
                    <a href="#" class="cart-btn">Checkout</a>   {% comment %}оформление заказа  {% endcomment %}
                {% endif %}
            {% endwith %}
        </div>
    </section>
{% endblock content%}

elit/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        {% comment %} bootstrap {% endcomment %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        {% comment %} local css {% endcomment %}
        <link rel="stylesheet" href="{% static 'scss/base.css' %}">
        <script src="{% static 'js/base.js' %}"></script>
        {% comment %} favicon {% endcomment %}
       
    </head>
    <body>
        <header class="header sticky-top">
            <div class="header-container d-flex">
                <nav class="header-nav pt-4">
                    <ul  class="header-list d-flex">
                        <li>
                            <a href="/" class="nav-a m-3">Home</a>
                        </li>
                        <li>
                            <a href="#" class="nav-a m-3">Shop</a>
                        </li>
                    </ul>
                </nav>
                 <div class="header-logo">
                    <a href="/"><img src="{% static 'img/Picsart_25.png' %}" alt="" class="elit-logo"></a> 
                </div>  
                <div class="header-profile pt-2">
                    <a href="{% url 'cart:cart_detail' %}"><img src="{% static 'img/cart_online.png' %}" alt="" class="grob"></a>
                    <a href="#" class="m-2">LOGIN</a>
                        {% comment %} {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}" class="m-2">LOGOUT</a>
                        {% else %}
                            <a href="{% url 'login' %}" class="m-2">LOGIN</a>
                        {% endif %} {% endcomment %}
                    {% comment %} иконка что будет вести в корзину {% endcomment %}
                    <p class="cart-quantity">
                        {% with cart_quantity=cart|length %}
                            {% if cart_quantity > 0 %}
                                {{ cart_quantity }}
                            {% else %}
                                0 {% comment %} 0 если товара нет {% endcomment %}
                            {% endif %}
                        {% endwith %}
                    </p>
                </div>    
            </div>
        </header>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
        {% comment %} <img src="{% static 'img/frame2.png' %}" alt="" class="frame2"> {% endcomment %}
       {% comment %} <footer class="footer d-flex justify-content-center align-items-center">
            <p class="footer-text">© 2025 Elit. All rights reserved.</p> {% endcomment %}
        {% comment %} js for bootstrap {% endcomment %}
        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

{% comment %} main –> src src/assets/css, img  {% endcomment %}

elit/main/templates/main/index/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
    <section class="search d-flex gap-4 p-4" ">
            <!-- Кнопка-круг -->
        <div class="home-title">
            <a href="#" id="expandLink" class="home-link-circle">ALL<br>hPRODUCTS</a>
        </div>
            <!-- Пошук -->
        <div class="home-search">
            <form class="d-flex">
                <input type="search" class='form-control' placeholder="Search for products">
            </form>
        </div> 
    </section>
    
    <section class="home d-flex flex-column">
        <div class="home-recomendation">
            <div class="rec-title mb-4">
                <h3><span>Popular Accessories</span></h3>
            </div>
        </div>
        <div class="home-cards d-flex gap-4">
            {% comment %}Відображення карток товарів. Ітерує по всіх products, кожен виводиться як картка з посиланням. {% endcomment %}
            {% for product in products %}
                <a href="{{ product.get_absolute_url }}" class="home-card d-flex flex-column align-items-center">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" class="card-img" alt="">
                    {% comment %} Назва та ціна. Якщо є знижка — стара ціна зачеркнута, поруч нова.
Інакше просто виводиться ціна. {% endcomment %}
                    <h5 class="title-card">{{ product.name }}</h5>
                    {% if product.discount %}
                        <div class="cart-discount d-flex gap-2"> 
                            <p class="line">$ {{ product.price }}</p>
                            <p>$ {{ product.sell_price }}</p>
                        </div>
                    {% else %}
                        <p class="price">$ {{ product.price }}</p>
                    {% endif %}
                </a>
            {% endfor %}
        </div>
        <div class="bot-title d-flex flex-column align-items-center">
            <a href="#" class="bot-btn mt-4">botshop</a>
        </div>
    </section>
    {% comment %} <img src="{% static 'img/logobot.png' %}" class="logogothic" alt=""> {% endcomment %}
    {% comment %} <img src="{% static 'img/logobot.png' %}" class="subtitlee" alt=""> {% endcomment %}
{% endblock content %}

{% comment %} главная страница,  {% endcomment %}

{% comment %} Цей шаблон home.html — це головна сторінка інтернет-магазину, написана з використанням Django Template Language. Він відповідає за відображення кнопки переходу до всіх товарів, секції з популярними товарами та нижньої кнопки (бот-магазин). {% endcomment %}

elit/main/templates/main/product/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <div class="detail_product d-flex">
        <div class="detail-img">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" alt="" class="detail-image">
        </div>
        <div class="detail-description">
            <h2>{{ product.name }}</h2>
            <h3>Category: {{ product.category }}</h3>
            <p>Description: {{ product.description|linebreaks }}</p>
            {% if product.discount %}
                <div class="cart-discount d-flex gap-2"> 
                    <p class="line">$ {{ product.price }}</p>
                    <p>$ {{ product.sell_price }}</p>
                </div>
            {% else %}
                <p class="price">$ {{ product.price }}</p>
            {% endif %}
            <form action="{% url 'cart:cart_add' product.id %}" method="POST" class="qform">
                <div class="cart-form">
                    {{ cart_product_form}}
                    {% csrf_token %} 
                </div>
                <input type="submit" value="Add to cart" class="add-to-cart-btn ">
            </form>
        </div>
    </div>
{% endblock content %}

{% comment %} Цей шаблон відображає детальну сторінку товару у Django. Він містить інформацію про зображення, назву, категорію, опис, ціну (враховуючи знижку) і форму додавання до кошика.  {% endcomment %}

{% comment %} Проблема/Потенціал	Рекомендація
❗ class="detail_product"	Виправ: CSS-класи мають бути через - — краще detail-product
🔁 product.category	Можна вивести product.category.name, якщо використовує ForeignKey
✅ Додати кількість на складі	Виводити product.stock чи available (якщо є така модельна логіка)
⚙️ Зробити кнопку disabled	Якщо товар відсутній (через if product.available) {% endcomment %}

elit/main/templates/main/product/list.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Shop{% endblock title %}

{% block content %}
<div class="llist d-flex">
    <div class="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'main:product_list' %}">All</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="main">
        <div class="main-title">
            {% if category %}{{ category.name }}{% else %}Products{% endif %}
        </div>
        <div class="product-list">
            <div class="items">
                {% for product in products %}
                    <div class="item">
                        <a href="{{ product.get_absolute_url }}" class="home-card d-flex flex-column align-items-center text-center">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" class="card-img" alt="">
                            <h5 class="title-card">{{ product.name }}</h5>
                            {% if product.discount %}
                                <div class="cart-discount d-flex gap-2"> 
                                    <p class="line">$ {{ product.price }}</p>
                                    <p>$ {{ product.sell_price }}</p>
                                </div>
                            {% else %}
                                <p class="price">$ {{ product.price }}</p>
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% comment %} пагинация страниц = отображение списком на одной странице{% endcomment %}
        <ul class="pagination">
            <li class="{% if not products.has_previous %}disabled{% endif %}">
                <a href="{% if products.has_previous %}?page={{ products.previous_page_number }}{% endif %}">Previous</a>
            </li>
            {% for page in products.paginator.page_range %}
                {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                    <li>
                        <a href="?page={{ page }}" class="{% if products.number == page %}disabled{% endif %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="{% if not products.has_next %}disabled{% endif %}">
                <a href="{% if products.has_next %}?page={{products.next_page_number}}{% endif %}">Next</a>
            </li>
        </ul>
    </div>
</div>
{% endblock content %}

{% comment %} веостаем тут наш каталог {% endcomment %}